import { useCallback, useEffect, useState, type ReactNode } from "react";
import { apiClient, type FinanceReportDashboardData } from "@/lib/api";
import { useAuth } from "@/contexts/AuthContext";
import DashboardHeader from "@/components/DashboardHeader";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useToast } from "@/hooks/use-toast";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from "recharts";
import {
  IndianRupee,
  Wallet,
  Undo2,
  Clock3,
  ReceiptText,
  Loader2,
  FileDown,
  FileSpreadsheet,
  RefreshCw,
  Building2,
  FlaskConical,
  Info,
  BarChart3,
} from "lucide-react";
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

const NAVY = "#1e4d8c";
const OCEAN = "#1d6fa3";
const DONUT_COLORS = ["#1e4d8c", "#1d6fa3", "#334155", "#2563eb", "#64748b", "#0ea5e9", "#0f172a"];

const PRESETS: Array<{ value: string; label: string }> = [
  { value: "today", label: "Today" },
  { value: "yesterday", label: "Yesterday" },
  { value: "this_week", label: "This week" },
  { value: "this_month", label: "This month" },
  { value: "this_quarter", label: "This quarter" },
  { value: "this_financial_year", label: "This financial year" },
];

function fmtMoney(value: number | null | undefined): string {
  const n = Number(value ?? 0);
  if (!Number.isFinite(n)) return "0.00";
  return n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function todayStr(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}

function monthStartStr(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-01`;
}

function formatDateTimeDisplay(iso: string | null | undefined): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
  } catch {
    return String(iso);
  }
}

function exportFinanceReportExcel(data: FinanceReportDashboardData): void {
  const meta = data.meta;
  const wb = XLSX.utils.book_new();

  const summaryRows: Array<Array<string | number>> = [
    [meta.institute_name],
    [meta.report_title],
    [`Period: ${meta.date_from} to ${meta.date_to}`],
    [`Generated: ${new Date(meta.generated_at).toLocaleString()}`],
    [`Generated by: ${meta.generated_by}`],
    [],
    ["Summary metric", "Value"],
    ["Total revenue (INR)", data.summary.total_revenue],
    ["Internal revenue (INR)", data.summary.internal_revenue],
    ["External revenue (INR)", data.summary.external_revenue],
    ["Wallet recharges — approved (INR)", data.summary.wallet_recharges],
    ["Pending payments (INR)", data.summary.pending_payments],
    ["Refunded amount (INR)", data.summary.refunded_amount],
    ["Outstanding dues (INR)", data.summary.outstanding_dues],
    ["Booking count", data.summary.booking_count],
    ["Avg. booking value (INR)", data.summary.avg_booking_value],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryRows);
  wsSummary["!cols"] = [{ wch: 34 }, { wch: 20 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

  const trendRows: Array<Array<string | number>> = [
    ["Date", "Revenue (INR)"],
    ...data.charts.revenue_trend.map((r) => [r.date, r.revenue]),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(trendRows), "Revenue Trend");

  const deptRows: Array<Array<string | number>> = [
    ["Department", "Revenue (INR)", "Bookings"],
    ...data.tables.internal_by_department.map((r) => [r.name, r.revenue, r.bookings]),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(deptRows), "Internal by Department");

  const intEquipRows: Array<Array<string | number>> = [
    ["Equipment", "Code", "Revenue (INR)", "Bookings"],
    ...data.tables.internal_by_equipment.map((r) => [r.name, r.code, r.revenue, r.bookings]),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(intEquipRows), "Internal by Equipment");

  const extRows: Array<Array<string | number>> = [
    ["External category", "Revenue (INR)", "Bookings"],
    ...data.tables.external_by_category.map((r) => [r.name, r.revenue, r.bookings]),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(extRows), "External by Category");

  const eqAnalysisRows: Array<Array<string | number>> = [
    ["Equipment", "Code", "Revenue (INR)", "Bookings", "Booking hours"],
    ...data.tables.equipment_analysis.map((r) => [r.name, r.code, r.revenue, r.bookings, r.booking_hours]),
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(eqAnalysisRows), "Equipment Analysis");

  const pa = data.tables.payment_analytics;
  const paRows: Array<Array<string | number>> = [
    ["Payment analytics metric", "Amount (INR)"],
    ["Wallet recharge — approved", pa.wallet_recharge_approved],
    ["Wallet recharge — pending", pa.wallet_recharge_pending],
    ["Wallet recharge — rejected", pa.wallet_recharge_rejected],
    ["Wallet recharge — cancelled", pa.wallet_recharge_cancelled],
    ["Project grant", pa.project_grant],
    ["Direct cash deposit", pa.direct_cash_deposit],
    ["Online payments", pa.online_payments],
  ];
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(paRows), "Payment Analytics");

  XLSX.writeFile(wb, `finance-report-${meta.date_from}-to-${meta.date_to}.xlsx`);
}

function exportFinanceReportPdf(data: FinanceReportDashboardData): void {
  const meta = data.meta;
  const doc = new jsPDF({ orientation: "portrait", unit: "pt", format: "a4" });

  doc.setFontSize(14);
  doc.setTextColor(15, 118, 110);
  doc.text(meta.institute_name, 40, 40);
  doc.setFontSize(12);
  doc.setTextColor(30, 41, 59);
  doc.text(meta.report_title, 40, 58);
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(`Period: ${meta.date_from} to ${meta.date_to}`, 40, 74);
  doc.text(`Generated: ${new Date(meta.generated_at).toLocaleString()}`, 40, 88);
  doc.text(`Generated by: ${meta.generated_by}`, 40, 102);

  autoTable(doc, {
    startY: 116,
    head: [["Summary metric", "Amount (INR)"]],
    body: [
      ["Total revenue", fmtMoney(data.summary.total_revenue)],
      ["Internal revenue", fmtMoney(data.summary.internal_revenue)],
      ["External revenue", fmtMoney(data.summary.external_revenue)],
      ["Wallet recharges (approved)", fmtMoney(data.summary.wallet_recharges)],
      ["Pending payments", fmtMoney(data.summary.pending_payments)],
      ["Refunded amount", fmtMoney(data.summary.refunded_amount)],
      ["Outstanding dues", fmtMoney(data.summary.outstanding_dues)],
      ["Booking count", String(data.summary.booking_count)],
      ["Avg. booking value", fmtMoney(data.summary.avg_booking_value)],
    ],
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [15, 118, 110], textColor: 255 },
    margin: { left: 40, right: 40 },
  });

  type DocWithAutoTable = { lastAutoTable: { finalY: number } };
  let y = (doc as unknown as DocWithAutoTable).lastAutoTable.finalY + 24;

  const addSection = (title: string, head: string[], body: Array<Array<string | number>>) => {
    if (body.length === 0) return;
    if (y > 700) {
      doc.addPage();
      y = 40;
    }
    doc.setFontSize(11);
    doc.setTextColor(15, 118, 110);
    doc.text(title, 40, y);
    autoTable(doc, {
      startY: y + 8,
      head: [head],
      body,
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [51, 65, 85], textColor: 255 },
      margin: { left: 40, right: 40 },
    });
    y = (doc as unknown as DocWithAutoTable).lastAutoTable.finalY + 24;
  };

  addSection(
    "Internal revenue by department",
    ["Department", "Revenue (INR)", "Bookings"],
    data.tables.internal_by_department.map((r) => [r.name, fmtMoney(r.revenue), r.bookings]),
  );
  addSection(
    "Internal revenue by equipment",
    ["Equipment", "Code", "Revenue (INR)", "Bookings"],
    data.tables.internal_by_equipment.map((r) => [r.name, r.code, fmtMoney(r.revenue), r.bookings]),
  );
  addSection(
    "External revenue by category",
    ["Category", "Revenue (INR)", "Bookings"],
    data.tables.external_by_category.map((r) => [r.name, fmtMoney(r.revenue), r.bookings]),
  );
  addSection(
    "Equipment analysis",
    ["Equipment", "Code", "Revenue (INR)", "Bookings", "Booking hours"],
    data.tables.equipment_analysis.map((r) => [r.name, r.code, fmtMoney(r.revenue), r.bookings, r.booking_hours]),
  );

  const pa = data.tables.payment_analytics;
  addSection(
    "Payment analytics",
    ["Metric", "Amount (INR)"],
    [
      ["Wallet recharge — approved", fmtMoney(pa.wallet_recharge_approved)],
      ["Wallet recharge — pending", fmtMoney(pa.wallet_recharge_pending)],
      ["Wallet recharge — rejected", fmtMoney(pa.wallet_recharge_rejected)],
      ["Wallet recharge — cancelled", fmtMoney(pa.wallet_recharge_cancelled)],
      ["Project grant", fmtMoney(pa.project_grant)],
      ["Direct cash deposit", fmtMoney(pa.direct_cash_deposit)],
      ["Online payments", fmtMoney(pa.online_payments)],
    ],
  );

  doc.save(`finance-report-${meta.date_from}-to-${meta.date_to}.pdf`);
}

interface KpiCardProps {
  label: string;
  value: string;
  hint?: string;
  icon: ReactNode;
  accent?: string;
}

function KpiCard({ label, value, hint, icon, accent }: KpiCardProps) {
  return (
    <div className="rounded-xl border bg-card p-4 shadow-sm">
      <div className="flex items-center justify-between">
        <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p>
        {icon}
      </div>
      <p className={`mt-1 text-2xl font-bold ${accent ?? "text-slate-900 dark:text-slate-100"}`}>₹{value}</p>
      {hint ? <p className="mt-1 text-xs text-muted-foreground">{hint}</p> : null}
    </div>
  );
}

const FinanceReports = () => {
  const { user } = useAuth();
  const { toast } = useToast();

  const [preset, setPreset] = useState<string>("this_month");
  const [customFrom, setCustomFrom] = useState<string>(monthStartStr());
  const [customTo, setCustomTo] = useState<string>(todayStr());

  const [data, setData] = useState<FinanceReportDashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [exportingExcel, setExportingExcel] = useState(false);
  const [exportingPdf, setExportingPdf] = useState(false);

  const fetchReport = useCallback(
    async (params: { preset?: string; date_from?: string; date_to?: string }) => {
      setLoading(true);
      const res = await apiClient.getFinanceReportDashboard(params);
      if (res.error) {
        toast({ title: "Unable to load report", description: res.error, variant: "destructive" });
        setData(null);
      } else if (res.data) {
        setData(res.data);
      }
      setLoading(false);
    },
    [toast],
  );

  useEffect(() => {
    void fetchReport({ preset: "this_month" });
    // Load once on mount; subsequent loads are user-triggered via preset/custom-range controls.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePresetClick = (value: string) => {
    setPreset(value);
    void fetchReport({ preset: value });
  };

  const handleApplyCustomRange = () => {
    if (!customFrom || !customTo) {
      toast({ title: "Select both dates", description: "Please choose a from and to date.", variant: "destructive" });
      return;
    }
    setPreset("custom");
    void fetchReport({ preset: "custom", date_from: customFrom, date_to: customTo });
  };

  const handleRefresh = () => {
    if (preset === "custom") {
      void fetchReport({ preset: "custom", date_from: customFrom, date_to: customTo });
    } else {
      void fetchReport({ preset });
    }
  };

  const handleExportExcel = () => {
    if (!data) return;
    setExportingExcel(true);
    try {
      exportFinanceReportExcel(data);
    } finally {
      setExportingExcel(false);
    }
  };

  const handleExportPdf = () => {
    if (!data) return;
    setExportingPdf(true);
    try {
      exportFinanceReportPdf(data);
    } finally {
      setExportingPdf(false);
    }
  };

  const internalVsExternalData = data?.charts.internal_vs_external ?? [];
  const revenueByOrgCategoryData = data?.charts.revenue_by_org_category ?? [];
  const revenueByDepartmentData = data?.charts.revenue_by_department ?? [];
  const equipmentRevenueData = (data?.charts.equipment_revenue ?? []).slice(0, 10);
  const revenueTrendData = data?.charts.revenue_trend ?? [];

  return (
    <div className="page-shell">
      <DashboardHeader />
      <main className="container mx-auto px-4 py-8 max-w-7xl">
        <div className="mb-8 rounded-2xl bg-gradient-to-r from-primary via-primary to-accent p-6 sm:p-8 text-white shadow-xl">
          <h1 className="text-2xl sm:text-3xl font-semibold tracking-tight">Finance Reports</h1>
          <p className="mt-2 text-white/85 text-sm sm:text-base max-w-3xl">
            Departmental revenue, wallet recharges, and payment analytics for{" "}
            {user?.department_name || "your department"}. Choose a period and export the executive summary as Excel
            or PDF.
          </p>
        </div>

        <Card className="mb-6">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-primary" />
              Report period
            </CardTitle>
            <CardDescription>Pick a preset range or set a custom date range, then export the report.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex flex-wrap gap-2">
              {PRESETS.map((p) => (
                <Button
                  key={p.value}
                  type="button"
                  size="sm"
                  variant={preset === p.value ? "default" : "outline"}
                  className={preset === p.value ? "bg-primary hover:bg-primary/90 text-white" : ""}
                  onClick={() => handlePresetClick(p.value)}
                  disabled={loading}
                >
                  {p.label}
                </Button>
              ))}
            </div>
            <div className="flex flex-wrap items-end gap-3 border-t pt-4">
              <div className="space-y-2">
                <Label>Custom from</Label>
                <Input
                  type="date"
                  value={customFrom}
                  onChange={(e) => setCustomFrom(e.target.value)}
                  className="w-40"
                />
              </div>
              <div className="space-y-2">
                <Label>Custom to</Label>
                <Input type="date" value={customTo} onChange={(e) => setCustomTo(e.target.value)} className="w-40" />
              </div>
              <Button
                type="button"
                variant={preset === "custom" ? "default" : "outline"}
                className={preset === "custom" ? "bg-primary hover:bg-primary/90 text-white" : ""}
                onClick={handleApplyCustomRange}
                disabled={loading}
              >
                Apply custom range
              </Button>
              <div className="ml-auto flex flex-wrap gap-2">
                <Button type="button" variant="secondary" onClick={handleRefresh} disabled={loading}>
                  {loading ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <RefreshCw className="h-4 w-4 mr-2" />}
                  Refresh
                </Button>
                <Button
                  type="button"
                  variant="outline"
                  onClick={handleExportExcel}
                  disabled={!data || loading || exportingExcel}
                >
                  {exportingExcel ? (
                    <Loader2 className="h-4 w-4 animate-spin mr-2" />
                  ) : (
                    <FileSpreadsheet className="h-4 w-4 mr-2" />
                  )}
                  Export Excel
                </Button>
                <Button type="button" variant="outline" onClick={handleExportPdf} disabled={!data || loading || exportingPdf}>
                  {exportingPdf ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <FileDown className="h-4 w-4 mr-2" />}
                  Export PDF
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {loading && !data ? (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="h-10 w-10 animate-spin text-primary" />
          </div>
        ) : !data ? (
          <Card>
            <CardContent className="py-12 text-center text-muted-foreground">
              No report data available for this period.
            </CardContent>
          </Card>
        ) : (
          <div className={loading ? "relative opacity-60 pointer-events-none" : undefined}>
            {loading && (
              <div className="absolute inset-0 z-10 flex items-start justify-center pt-24 bg-background/30">
                <Loader2 className="h-10 w-10 animate-spin text-primary" />
              </div>
            )}

            {data.meta.note ? (
              <Alert className="mb-6">
                <Info className="h-4 w-4" />
                <AlertTitle>Note</AlertTitle>
                <AlertDescription>{data.meta.note}</AlertDescription>
              </Alert>
            ) : null}

            <div className="mb-6 rounded-xl border bg-gradient-to-br from-slate-900 via-slate-800 to-primary p-6 text-white shadow-lg">
              <p className="text-sm font-medium uppercase tracking-wider text-sky-100/90">{data.meta.institute_name}</p>
              <h3 className="mt-2 text-2xl font-bold tracking-tight">{data.meta.report_title}</h3>
              <div className="mt-3 flex flex-wrap gap-x-6 gap-y-1 text-sm text-slate-300">
                <span>
                  <span className="font-semibold text-slate-200">Period: </span>
                  {data.meta.date_from} – {data.meta.date_to}
                </span>
                <span>
                  <span className="font-semibold text-slate-200">Generated: </span>
                  {formatDateTimeDisplay(data.meta.generated_at)}
                </span>
                <span>
                  <span className="font-semibold text-slate-200">By: </span>
                  {data.meta.generated_by}
                </span>
              </div>
            </div>

            {/* KPI summary cards */}
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-8">
              <KpiCard
                label="Total revenue"
                value={fmtMoney(data.summary.total_revenue)}
                hint={`${data.summary.booking_count} booking(s) · avg ₹${fmtMoney(data.summary.avg_booking_value)}`}
                icon={<IndianRupee className="h-4 w-4 text-primary" />}
                accent="text-primary dark:text-sky-200"
              />
              <KpiCard
                label="Internal revenue"
                value={fmtMoney(data.summary.internal_revenue)}
                hint="Students / faculty"
                icon={<Building2 className="h-4 w-4 text-slate-600" />}
              />
              <KpiCard
                label="External revenue"
                value={fmtMoney(data.summary.external_revenue)}
                hint="RND / Industry / Educational / Other"
                icon={<FlaskConical className="h-4 w-4 text-accent" />}
              />
              <KpiCard
                label="Wallet recharges"
                value={fmtMoney(data.summary.wallet_recharges)}
                hint="Approved in period"
                icon={<Wallet className="h-4 w-4 text-emerald-600" />}
                accent="text-emerald-700 dark:text-emerald-300"
              />
              <KpiCard
                label="Pending payments"
                value={fmtMoney(data.summary.pending_payments)}
                hint="Awaiting payment"
                icon={<Clock3 className="h-4 w-4 text-amber-600" />}
                accent="text-amber-700 dark:text-amber-300"
              />
              <KpiCard
                label="Refunded amount"
                value={fmtMoney(data.summary.refunded_amount)}
                hint="Refunded bookings in period"
                icon={<Undo2 className="h-4 w-4 text-rose-600" />}
                accent="text-rose-700 dark:text-rose-300"
              />
              <KpiCard
                label="Outstanding dues"
                value={fmtMoney(data.summary.outstanding_dues)}
                hint="Unsettled amount due"
                icon={<ReceiptText className="h-4 w-4 text-orange-600" />}
                accent="text-orange-700 dark:text-orange-300"
              />
              <KpiCard
                label="Avg. booking value"
                value={fmtMoney(data.summary.avg_booking_value)}
                hint={`${data.summary.booking_count} revenue booking(s)`}
                icon={<BarChart3 className="h-4 w-4 text-slate-600" />}
              />
            </div>

            {/* Charts */}
            <div className="grid lg:grid-cols-2 gap-6 mb-6">
              <Card>
                <CardHeader>
                  <CardTitle>Revenue trend</CardTitle>
                  <CardDescription>Revenue over the selected period</CardDescription>
                </CardHeader>
                <CardContent>
                  {revenueTrendData.length === 0 ? (
                    <p className="text-center text-muted-foreground py-12">No revenue in this period</p>
                  ) : (
                    <ResponsiveContainer width="100%" height={300}>
                      <LineChart data={revenueTrendData} margin={{ top: 8, right: 16, left: 8, bottom: 8 }}>
                        <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                        <XAxis dataKey="date" tick={{ fontSize: 11 }} />
                        <YAxis tick={{ fontSize: 11 }} tickFormatter={(v) => `₹${v}`} />
                        <Tooltip formatter={(v: number) => [`₹${fmtMoney(v)}`, "Revenue"]} />
                        <Line type="monotone" dataKey="revenue" stroke={NAVY} strokeWidth={2} dot={false} />
                      </LineChart>
                    </ResponsiveContainer>
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Internal vs external</CardTitle>
                  <CardDescription>Share of revenue by user category</CardDescription>
                </CardHeader>
                <CardContent>
                  {internalVsExternalData.every((d) => !d.value) ? (
                    <p className="text-center text-muted-foreground py-12">No revenue in this period</p>
                  ) : (
                    <ResponsiveContainer width="100%" height={300}>
                      <PieChart>
                        <Pie
                          data={internalVsExternalData}
                          cx="50%"
                          cy="50%"
                          innerRadius={60}
                          outerRadius={110}
                          paddingAngle={2}
                          dataKey="value"
                          nameKey="name"
                          label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                        >
                          {internalVsExternalData.map((_, i) => (
                            <Cell key={i} fill={i === 0 ? NAVY : OCEAN} />
                          ))}
                        </Pie>
                        <Tooltip formatter={(v: number) => [`₹${fmtMoney(v)}`, "Revenue"]} />
                      </PieChart>
                    </ResponsiveContainer>
                  )}
                </CardContent>
              </Card>
            </div>

            <div className="grid lg:grid-cols-2 gap-6 mb-6">
              <Card>
                <CardHeader>
                  <CardTitle>Revenue by department</CardTitle>
                  <CardDescription>Equipment home department (settled via your department)</CardDescription>
                </CardHeader>
                <CardContent>
                  {revenueByDepartmentData.length === 0 ? (
                    <p className="text-center text-muted-foreground py-12">No revenue in this period</p>
                  ) : (
                    <ResponsiveContainer width="100%" height={Math.max(260, revenueByDepartmentData.length * 40)}>
                      <BarChart
                        data={revenueByDepartmentData}
                        layout="vertical"
                        margin={{ top: 4, right: 16, left: 8, bottom: 4 }}
                      >
                        <CartesianGrid strokeDasharray="3 3" className="stroke-muted" horizontal={false} />
                        <XAxis type="number" tickFormatter={(v) => `₹${v}`} tick={{ fontSize: 11 }} />
                        <YAxis type="category" dataKey="name" width={140} tick={{ fontSize: 11 }} />
                        <Tooltip formatter={(v: number) => [`₹${fmtMoney(v)}`, "Revenue"]} />
                        <Bar dataKey="revenue" name="Revenue" fill={NAVY} radius={[0, 4, 4, 0]} />
                      </BarChart>
                    </ResponsiveContainer>
                  )}
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>Revenue by organization category</CardTitle>
                  <CardDescription>Split by user type (share of total revenue)</CardDescription>
                </CardHeader>
                <CardContent>
                  {revenueByOrgCategoryData.length === 0 ? (
                    <p className="text-center text-muted-foreground py-12">No revenue in this period</p>
                  ) : (
                    <ResponsiveContainer width="100%" height={300}>
                      <PieChart margin={{ top: 8, right: 8, bottom: 8, left: 8 }}>
                        <Pie
                          data={revenueByOrgCategoryData}
                          dataKey="revenue"
                          nameKey="name"
                          cx="50%"
                          cy="45%"
                          outerRadius={90}
                          label={false}
                          labelLine={false}
                        >
                          {revenueByOrgCategoryData.map((_, i) => (
                            <Cell key={i} fill={DONUT_COLORS[i % DONUT_COLORS.length]} />
                          ))}
                        </Pie>
                        <Tooltip
                          formatter={(value: number, _name: string, entry) => {
                            const pct = (entry?.payload as { pct?: number })?.pct ?? 0;
                            return [`₹${fmtMoney(value)} (${pct}%)`, (entry?.payload as { name?: string })?.name ?? ""];
                          }}
                        />
                        <Legend
                          layout="vertical"
                          verticalAlign="middle"
                          align="right"
                          wrapperStyle={{ paddingLeft: 8, fontSize: 12 }}
                          formatter={(value, entry) => {
                            const pct = (entry?.payload as { pct?: number })?.pct ?? 0;
                            return `${value} (${pct}%)`;
                          }}
                        />
                      </PieChart>
                    </ResponsiveContainer>
                  )}
                </CardContent>
              </Card>
            </div>

            <Card className="mb-6">
              <CardHeader>
                <CardTitle>Top equipment by revenue</CardTitle>
                <CardDescription>Highest-earning instruments in this period</CardDescription>
              </CardHeader>
              <CardContent>
                {equipmentRevenueData.length === 0 ? (
                  <p className="text-center text-muted-foreground py-12">No revenue in this period</p>
                ) : (
                  <ResponsiveContainer width="100%" height={Math.max(260, equipmentRevenueData.length * 34)}>
                    <BarChart
                      data={equipmentRevenueData}
                      layout="vertical"
                      margin={{ top: 4, right: 16, left: 8, bottom: 4 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" className="stroke-muted" horizontal={false} />
                      <XAxis type="number" tickFormatter={(v) => `₹${v}`} tick={{ fontSize: 11 }} />
                      <YAxis
                        type="category"
                        dataKey="code"
                        width={90}
                        tick={{ fontSize: 11 }}
                        tickFormatter={(v: string) => v}
                      />
                      <Tooltip
                        formatter={(v: number) => [`₹${fmtMoney(v)}`, "Revenue"]}
                        labelFormatter={(_label, payload) => (payload?.[0]?.payload as { name?: string })?.name ?? ""}
                      />
                      <Bar dataKey="revenue" name="Revenue" fill={OCEAN} radius={[0, 4, 4, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                )}
              </CardContent>
            </Card>

            {/* Tables */}
            <div className="grid lg:grid-cols-2 gap-6 mb-6">
              <Card>
                <CardHeader>
                  <CardTitle>Internal revenue by department</CardTitle>
                </CardHeader>
                <CardContent className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Department</TableHead>
                        <TableHead className="text-right">Bookings</TableHead>
                        <TableHead className="text-right">Revenue</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {data.tables.internal_by_department.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={3} className="text-center text-muted-foreground py-8">
                            No internal revenue in this period.
                          </TableCell>
                        </TableRow>
                      ) : (
                        data.tables.internal_by_department.map((r, idx) => (
                          <TableRow key={`${r.name}-${idx}`}>
                            <TableCell className="font-medium">{r.name}</TableCell>
                            <TableCell className="text-right">{r.bookings}</TableCell>
                            <TableCell className="text-right">₹{fmtMoney(r.revenue)}</TableCell>
                          </TableRow>
                        ))
                      )}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>External revenue by category</CardTitle>
                </CardHeader>
                <CardContent className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow>
                        <TableHead>Category</TableHead>
                        <TableHead className="text-right">Bookings</TableHead>
                        <TableHead className="text-right">Revenue</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {data.tables.external_by_category.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={3} className="text-center text-muted-foreground py-8">
                            No external revenue in this period.
                          </TableCell>
                        </TableRow>
                      ) : (
                        data.tables.external_by_category.map((r, idx) => (
                          <TableRow key={`${r.name}-${idx}`}>
                            <TableCell className="font-medium">{r.name}</TableCell>
                            <TableCell className="text-right">{r.bookings}</TableCell>
                            <TableCell className="text-right">₹{fmtMoney(r.revenue)}</TableCell>
                          </TableRow>
                        ))
                      )}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </div>

            <Card className="mb-6">
              <CardHeader>
                <CardTitle>Internal revenue by equipment</CardTitle>
              </CardHeader>
              <CardContent className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Equipment</TableHead>
                      <TableHead className="text-right">Bookings</TableHead>
                      <TableHead className="text-right">Revenue</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {data.tables.internal_by_equipment.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={3} className="text-center text-muted-foreground py-8">
                          No internal equipment revenue in this period.
                        </TableCell>
                      </TableRow>
                    ) : (
                      data.tables.internal_by_equipment.slice(0, 30).map((r, idx) => (
                        <TableRow key={`${r.code}-${idx}`}>
                          <TableCell className="font-medium">
                            <span className="font-mono text-xs text-muted-foreground mr-2">{r.code}</span>
                            {r.name}
                          </TableCell>
                          <TableCell className="text-right">{r.bookings}</TableCell>
                          <TableCell className="text-right">₹{fmtMoney(r.revenue)}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>

            <Card className="mb-6">
              <CardHeader>
                <CardTitle>Equipment analysis</CardTitle>
                <CardDescription>Revenue, bookings, and booking hours (utilisation proxy) per equipment</CardDescription>
              </CardHeader>
              <CardContent className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Equipment</TableHead>
                      <TableHead className="text-right">Bookings</TableHead>
                      <TableHead className="text-right">Booking hours</TableHead>
                      <TableHead className="text-right">Revenue</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {data.tables.equipment_analysis.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={4} className="text-center text-muted-foreground py-8">
                          No equipment activity in this period.
                        </TableCell>
                      </TableRow>
                    ) : (
                      data.tables.equipment_analysis.slice(0, 30).map((r, idx) => (
                        <TableRow key={`${r.code}-${idx}`}>
                          <TableCell className="font-medium">
                            <span className="font-mono text-xs text-muted-foreground mr-2">{r.code}</span>
                            {r.name}
                          </TableCell>
                          <TableCell className="text-right">{r.bookings}</TableCell>
                          <TableCell className="text-right">{r.booking_hours.toFixed(1)}h</TableCell>
                          <TableCell className="text-right">₹{fmtMoney(r.revenue)}</TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Payment analytics</CardTitle>
                <CardDescription>Wallet recharge pipeline and payment channels for this period</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Recharge — approved
                    </p>
                    <p className="mt-1 text-xl font-bold text-emerald-700 dark:text-emerald-300">
                      ₹{fmtMoney(data.tables.payment_analytics.wallet_recharge_approved)}
                    </p>
                  </div>
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Recharge — pending
                    </p>
                    <p className="mt-1 text-xl font-bold text-amber-700 dark:text-amber-300">
                      ₹{fmtMoney(data.tables.payment_analytics.wallet_recharge_pending)}
                    </p>
                  </div>
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Recharge — rejected
                    </p>
                    <p className="mt-1 text-xl font-bold text-rose-700 dark:text-rose-300">
                      ₹{fmtMoney(data.tables.payment_analytics.wallet_recharge_rejected)}
                    </p>
                  </div>
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Recharge — cancelled
                    </p>
                    <p className="mt-1 text-xl font-bold text-slate-700 dark:text-slate-300">
                      ₹{fmtMoney(data.tables.payment_analytics.wallet_recharge_cancelled)}
                    </p>
                  </div>
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Project grant</p>
                    <p className="mt-1 text-xl font-bold text-primary dark:text-sky-200">
                      ₹{fmtMoney(data.tables.payment_analytics.project_grant)}
                    </p>
                  </div>
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Direct cash deposit
                    </p>
                    <p className="mt-1 text-xl font-bold text-accent dark:text-sky-300">
                      ₹{fmtMoney(data.tables.payment_analytics.direct_cash_deposit)}
                    </p>
                  </div>
                  <div className="rounded-lg border bg-card p-4">
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Online payments
                    </p>
                    <p className="mt-1 text-xl font-bold text-slate-900 dark:text-slate-100">
                      ₹{fmtMoney(data.tables.payment_analytics.online_payments)}
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}
      </main>
    </div>
  );
};

export default FinanceReports;
